services:
  postgres:
    build:
      context: .
      dockerfile: postgresql_dockerfile
    container_name: postgres_web
    ports:
      - "2026:5432"
    environment:
      POSTGRES_USER: web_postgre
      POSTGRES_PASSWORD: web
      POSTGRES_DB: schema_web
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web_network

networks:
  web_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
